=== adovzh/cvgen/src/xml/cv-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright (c) 2011 Alexander Dovzhikov <alexander.dovzhikov@gmail.com>.
  ~ All rights reserved.
  ~
  ~ Redistribution and use in source and binary forms, with or without modification, are
  ~ permitted provided that the following conditions are met:
  ~
  ~    1. Redistributions of source code must retain the above copyright notice, this list of
  ~       conditions and the following disclaimer.
  ~
  ~    2. Redistributions in binary form must reproduce the above copyright notice, this list
  ~       of conditions and the following disclaimer in the documentation and/or other materials
  ~       provided with the distribution.
  ~
  ~ THIS SOFTWARE IS PROVIDED BY ALEXANDER DOVZHIKOV ''AS IS'' AND ANY EXPRESS OR IMPLIED
  ~ WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
  ~ FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL dovzhikov OR
  ~ CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  ~ CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  ~ SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
  ~ ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  ~ NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
  ~ ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  ~
  ~ cv-schema.xsd
  ~
  ~ Created on 06.09.2011 14:05:37
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="email_Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="phone_Type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="home"/>
            <xs:enumeration value="mobile"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="document">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="personal"/>
                <xs:element ref="education"/>
                <xs:element ref="objective"/>
                <xs:element ref="summary"/>
                <xs:element ref="skills"/>
                <xs:element ref="certifications"/>
                <xs:element ref="experience"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="personal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="first-name" type="xs:string"/>
                <xs:element name="last-name" type="xs:string"/>
                <xs:element ref="address"/>
                <xs:element ref="phone" maxOccurs="2"/>
                <xs:element name="email" type="email_Type"/>
                <xs:element name="birthday" type="xs:date"/>
                <xs:element name="marital-status" type="xs:string"/>
                <xs:element ref="languages"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" type="xs:string"/>
                <xs:element name="city" type="xs:string"/>
                <xs:element name="street" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="phone">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" type="phone_Type" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="languages">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="language" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="language">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="education">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="university"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="objective" type="xs:string"/>
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="university-name" type="xs:string"/>
                <xs:element name="start-date" type="xs:short"/>
                <xs:element name="end-date" type="xs:short"/>
                <xs:element name="department" type="xs:string"/>
                <xs:element name="specialty" type="xs:string"/>
                <xs:element name="level" type="xs:string"/>
                <xs:element name="thesis" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="summary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="summary-item" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="skills">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="skill-set" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="skill-set">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="skill-set-name" type="xs:string"/>
                <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="certifications">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cert-provider" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cert-provider">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cert" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="verify-url" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cert">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="date" type="xs:date" use="required"/>
                    <xs:attribute name="level" type="xs:string"/>
                    <xs:attribute name="expired" type="xs:boolean"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="experience">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="company" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="company-name" type="xs:string"/>
                <xs:element name="company-location" type="xs:string"/>
                <xs:element name="start-date" type="xs:string"/>
                <xs:element name="end-date" type="xs:string" minOccurs="0"/>
                <xs:element ref="project" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="project">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="project-name" type="xs:string"/>
                <xs:element name="role" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element ref="responsibilities"/>
                <xs:element ref="environment"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="responsibilities">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="responsibility" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="environment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="env-entry" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== adovzh/cvgen/src/xml/adovzhikov-cv.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright (c) 2011 Alexander Dovzhikov <alexander.dovzhikov@gmail.com>.
  ~ All rights reserved.
  ~
  ~ Redistribution and use in source and binary forms, with or without modification, are
  ~ permitted provided that the following conditions are met:
  ~
  ~    1. Redistributions of source code must retain the above copyright notice, this list of
  ~       conditions and the following disclaimer.
  ~
  ~    2. Redistributions in binary form must reproduce the above copyright notice, this list
  ~       of conditions and the following disclaimer in the documentation and/or other materials
  ~       provided with the distribution.
  ~
  ~ THIS SOFTWARE IS PROVIDED BY ALEXANDER DOVZHIKOV ''AS IS'' AND ANY EXPRESS OR IMPLIED
  ~ WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
  ~ FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL dovzhikov OR
  ~ CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  ~ CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  ~ SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
  ~ ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  ~ NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
  ~ ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  ~
  ~ adovzhikov-cv.xml
  ~
  ~ Created on 06.09.2011 14:37:17
  -->
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="cv-schema.xsd">
    <personal>
        <first-name>Alexander</first-name>
        <last-name>Dovzhikov</last-name>
        <address>
            <country>Russia</country>
            <city>St. Petersburg</city>
            <street>pr.Slavy,52/1 ap.240</street>
        </address>
        <phone type="home">+7 812 453 0557</phone>
        <phone type="mobile">+7 921 949 2660</phone>
        <email>alexander.dovzhikov@gmail.com</email>
        <birthday>1979-09-10</birthday>
        <marital-status>Married</marital-status>
        <languages>
            <language type="native">Russian</language>
            <language type="fluent">English</language>
        </languages>
    </personal>
    <education>
        <university>
            <university-name>Saint Petersburg State University</university-name>
            <start-date>1996</start-date>
            <end-date>2001</end-date>
            <department>Mathematics and Mechanics Faculty</department>
            <specialty>Computer Science</specialty>
            <level>Master of Science</level>
            <thesis>Online Training Development System</thesis>
        </university>
    </education>
    <objective>Senior Java Developer / Technical Lead position.</objective>
    <summary>
        <summary-item>Over 10 years of experience in software development</summary-item>
        <summary-item>Strong analytical skills and experience in Object Oriented concepts and programming techniques</summary-item>
        <summary-item>Strong mathematical background</summary-item>
        <summary-item>
            Extensive development experience in Java, J2EE, JSP, Servlet, EJB, JDBC, Struts,
            Spring Framework, Hibernate, XML, HTML, JavaScript for n-tier architecture
        </summary-item>
        <summary-item>
            Relational Database (RDBMS) concepts, database designing, normalization, PL/SQL,
            stored procedures, triggers and extensively worked with Oracle and MySQL
        </summary-item>
        <summary-item>
            Installation, configuration and administration knowledge of Apache Tomcat, Weblogic and Oracle
            Containers for J2EE (OC4J)
        </summary-item>
        <summary-item>Experience in Web services technologies like Apache Axis, SOAP, WSDL</summary-item>
        <summary-item>Experience in Derivatives Trading Systems development</summary-item>
        <summary-item>More than 5 years of experience working on Linux platform and shell scripting</summary-item>
        <summary-item>
            Hands-on experience leading all stages of system development efforts, including requirements
            definition, analysis, design, coding, implement reusable components, using third-party API,
            test-driven development, resolution of defects, integrate and test, build, deployment and support
        </summary-item>
        <summary-item>Mentor other members/juniors in the team</summary-item>
    </summary>
    <skills>
        <skill-set>
            <skill-set-name>Programming languages</skill-set-name>
            <skill>Java</skill>
            <skill>C/C++</skill>
            <skill>Clojure</skill>
            <skill>Python</skill>
            <skill>JavaScript</skill>
            <skill>Perl</skill>
            <skill>PHP</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>Technologies</skill-set-name>
            <skill>Core Java</skill>
            <skill>J2EE</skill>
            <skill>Swing</skill>
            <skill>JDBC</skill>
            <skill>XML/XSL</skill>
            <skill>JUnit</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>Frameworks</skill-set-name>
            <skill>Spring</skill>
            <skill>Hibernate</skill>
            <skill>Struts</skill>
            <skill>Tiles</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>Web Technologies</skill-set-name>
            <skill>JSP</skill>
            <skill>HTML</skill>
            <skill>XML</skill>
            <skill>JavaScript</skill>
            <skill>JSTL</skill>
            <skill>CSS</skill>
            <skill>Axis</skill>
            <skill>SOAP</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>RDBMS</skill-set-name>
            <skill>Oracle</skill>
            <skill>MySQL</skill>
            <skill>PostgreSQL</skill>
            <skill>MS SQL</skill>
            <skill>DB2</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>Application/Web Servers</skill-set-name>
            <skill>Weblogic</skill>
            <skill>Apache Tomcat</skill>
            <skill>OC4J</skill>
            <skill>JBoss</skill>
            <skill>Apache HTTP</skill>
            <skill>IIS</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>IDE</skill-set-name>
            <skill>IDEA</skill>
            <skill>NetBeans</skill>
            <skill>Eclipse</skill>
            <skill>JBuilder</skill>
            <skill>PL/SQL Developer</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>Platforms</skill-set-name>
            <skill>Linux Gentoo/Ubuntu/Fedora/Red Hat</skill>
            <skill>Windows 95/98/2000/XP/Vista</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>Version Control</skill-set-name>
            <skill>CVS</skill>
            <skill>Subversion</skill>
            <skill>Git</skill>
            <skill>Perforce</skill>
            <skill>ClearCase</skill>
            <skill>StarTeam</skill>
        </skill-set>
        <skill-set>
            <skill-set-name>Utilities/Tools</skill-set-name>
            <skill>Apache Ant</skill>
            <skill>Apache FOP</skill>
        </skill-set>
    </skills>
    <certifications>
        <cert-provider name="Sun">
            <cert date="2010-05-12">Sun Certified Developer for the Java Platform</cert>
            <cert date="2008-06-27">Sun Certified Programmer for the Java Platform, Standard Edition 6</cert>
        </cert-provider>
        <cert-provider name="Angelika Langer">
            <cert date="2010-07-05">High-Performance Java Course Certificate</cert>
        </cert-provider>
        <cert-provider name="Brainbench" verify-url="http://www.brainbench.com/transcript.jsp?pid=7441065">
            <cert date="2010-09-19" level="Master's">C</cert>
            <!--<cert date="2008-02-25" expired="true">C++</cert>-->
            <cert date="2008-12-06" level="Master's">Java 5</cert>
            <!--<cert date="2008-08-17" level="Master's" expired="true">Java 2 Fundamentals</cert>-->
            <cert date="2011-03-23" level="Master's">Java 2 - GUI</cert>
            <cert date="2009-02-01" level="Master's">Java 2 - Non-GUI</cert>
            <cert date="2009-04-09">Java 2 Platform, Enterprise Edition (J2EE)</cert>
            <cert date="2009-04-16">SQL (ANSI)</cert>
            <!--<cert date="2008-09-28" level="Master's">RDBMS Concepts</cert>-->
            <cert date="2008-10-18" level="Master's">Programming Concepts</cert>
            <cert date="2008-11-03">Programming/Analyst Aptitude</cert>
            <cert date="2008-12-01" level="Master's">OO Concepts</cert>
            <cert date="2009-02-15">Java Server Pages (JSP 1.2)</cert>
            <!--<cert date="2008-02-27" expired="true">Listening Comprehension English (UK)</cert>-->
            <!--<cert date="2008-08-24" expired="true">Written English</cert>-->
            <cert date="2009-02-01">Listening Skills</cert>
            <cert date="2009-07-26">Business Communication</cert>
            <cert date="2009-09-03">Customer Requirements Analysis</cert>
        </cert-provider>
    </certifications>
    <experience>
        <company>
            <company-name>Devexperts</company-name>
            <company-location>Saint Petersburg, Russia</company-location>
            <start-date>Apr 2008</start-date>
            <project>
                <project-name>Thinkorswim</project-name>
                <role>Senior Java Developer</role>
                <description>Financial software with support for investment and brokerage companies
                dealing in global futures, options, stock and FOREX trading</description>
                <responsibilities>
